import React from 'react'
import Head from 'next/head'
import Layout from '../components/Layout'
import { PRODUCT } from '../lib/product'

const CONTACT_EMAIL = 'hello@pricelens.app'
const EFFECTIVE_DATE = 'July 12, 2026'

export default function TermsOfService() {
  return (
    <Layout>
      <Head>
        <title>Terms of Service — {PRODUCT.name}</title>
        <meta name="description" content={`Terms of Service for ${PRODUCT.name}`} />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <article className="max-w-3xl mx-auto bg-white p-8 rounded-xl shadow prose-terms">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Effective date: {EFFECTIVE_DATE}</p>

        <p className="text-gray-700 mb-6">
          These Terms of Service (&ldquo;Terms&rdquo;) govern your use of {PRODUCT.name} (the &ldquo;Service&rdquo;).
          By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
        </p>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">1. The Service</h2>
          <p className="text-gray-700">
            {PRODUCT.name} is a pricing-analysis tool that returns a teardown of submitted pricing pages or plan
            copy. Results are generated by automated AI analysis and are provided for informational purposes only.
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Acceptable Use</h2>
          <p className="text-gray-700 mb-2">You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700">
            <li>Use the Service for any unlawful purpose or to violate others&rsquo; rights.</li>
            <li>Submit content that is defamatory, infringing, or contains personal data you are not authorized to share.</li>
            <li>Attempt to reverse-engineer, overload, or disrupt the Service or its infrastructure.</li>
            <li>Resell or redistribute the Service or its outputs without our written permission.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Accounts &amp; Subscriptions</h2>
          <p className="text-gray-700 mb-2">
            Paid plans (Pro, Studio) are billed through our payment processor, Waffo. By subscribing, you authorize
            recurring charges according to the plan you select. Prices are shown in USD unless stated otherwise.
          </p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700">
            <li>Subscriptions renew automatically until cancelled.</li>
            <li>You can cancel anytime from your account; access continues until the end of the paid period.</li>
            <li>We may change plan prices for future billing periods with notice; existing periods are unaffected.</li>
          </ul>
        </section>

        <section className="mb-8" id="refunds">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Refunds</h2>
          <p className="text-gray-700">
            Because the Service is delivered digitally and immediately upon payment, we generally do not offer
            refunds once a billing period has started. If you believe a charge was made in error, or the Service
            was unavailable through our fault, contact{' '}
            <a className="text-brand underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> within 14 days
            of the charge and we will review it fairly. Chargebacks opened without first contacting us may result
            in loss of account access.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Intellectual Property</h2>
          <p className="text-gray-700">
            The Service, its code, design, and branding are owned by us or our licensors. The teardown we generate
            for your inputs is provided to you for your own use. You retain ownership of the pricing content you
            submit; you grant us a limited license to process it to deliver the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Disclaimer &amp; Limitation of Liability</h2>
          <p className="text-gray-700 mb-2">
            The analysis is generated by AI and may be incomplete or inaccurate. It is <strong>not</strong> financial,
            legal, or business advice. You are solely responsible for any pricing decisions you make.
          </p>
          <p className="text-gray-700">
            To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential
            damages arising from your use of the Service. Our total liability is limited to the amount you paid in
            the 3 months before the claim.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Termination</h2>
          <p className="text-gray-700">
            We may suspend or terminate your access if you violate these Terms or use the Service unlawfully.
            You may stop using the Service and cancel your subscription at any time. Sections that by nature should
            survive termination will remain in effect.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Changes to These Terms</h2>
          <p className="text-gray-700">
            We may update these Terms. Material changes will be posted here with a revised effective date. Continued
            use after changes means you accept the updated Terms.
          </p>
        </section>

        <section className="mb-4">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Contact</h2>
          <p className="text-gray-700">
            Questions about these Terms? Email{' '}
            <a className="text-brand underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>
        </section>

        <p className="text-xs text-gray-400 mt-8 pt-4 border-t">
          Governing law: the laws of the jurisdiction in which the operator is established, without regard to conflict-of-law rules.
        </p>
      </article>
    </Layout>
  )
}
